version: '3'
services:
    main:
        image: jobhunt
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - .:/app
        ports:
            - 8000:8000
        depends_on:
            - startup
    startup:
        build:
            context: .
            dockerfile: Dockerfile
        image: jobhunt
        command: >
            sh -c "cp .env.example .env
                   php artisan key:generate
                   php artisan migrate:refresh --seed
                   npm install
                   npm run --cache /var/cache/ dev"
        volumes:
            - .:/app
        depends_on:
            - db
    db:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: admin
            MYSQL_ROOT: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: root
        # volumes:
        #     - ./storage/dbdata:/var/lib/mysql
        ports:
            - 3306:3306
        
